services:
  main-server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - MOCK_URL=http://mock-server:5001
    networks:
      - main

networks:
  main:
    name: yjhv
    external: true

