services:
  main-server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - MOCK_URL=http://mock-server:5001
  photo-service:
    hostname:
      people_counter
    build: 
      context: ./photoService
    ports:
      - "32000:32000"


